version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.11

jobs:
  test:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test

  deploy:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: 
          command: |
            sudo apt update   
            sudo apt -y -qq install awscli
      - aws-cli/configure
      - run: yarn build
      - run: yarn deploy

workflows:
  test-the-application:
    jobs:
      - test:
          filters:
            branches:
              ignore: master
  deploy-the-application:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master